require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CoffresController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Coffre. As you add validations to Coffre, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoffresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coffres as @coffres" do
      coffre = Coffre.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:coffres)).to eq([coffre])
    end
  end

  describe "GET show" do
    it "assigns the requested coffre as @coffre" do
      coffre = Coffre.create! valid_attributes
      get :show, {:id => coffre.to_param}, valid_session
      expect(assigns(:coffre)).to eq(coffre)
    end
  end

  describe "GET new" do
    it "assigns a new coffre as @coffre" do
      get :new, {}, valid_session
      expect(assigns(:coffre)).to be_a_new(Coffre)
    end
  end

  describe "GET edit" do
    it "assigns the requested coffre as @coffre" do
      coffre = Coffre.create! valid_attributes
      get :edit, {:id => coffre.to_param}, valid_session
      expect(assigns(:coffre)).to eq(coffre)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coffre" do
        expect {
          post :create, {:coffre => valid_attributes}, valid_session
        }.to change(Coffre, :count).by(1)
      end

      it "assigns a newly created coffre as @coffre" do
        post :create, {:coffre => valid_attributes}, valid_session
        expect(assigns(:coffre)).to be_a(Coffre)
        expect(assigns(:coffre)).to be_persisted
      end

      it "redirects to the created coffre" do
        post :create, {:coffre => valid_attributes}, valid_session
        expect(response).to redirect_to(Coffre.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coffre as @coffre" do
        post :create, {:coffre => invalid_attributes}, valid_session
        expect(assigns(:coffre)).to be_a_new(Coffre)
      end

      it "re-renders the 'new' template" do
        post :create, {:coffre => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coffre" do
        coffre = Coffre.create! valid_attributes
        put :update, {:id => coffre.to_param, :coffre => new_attributes}, valid_session
        coffre.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested coffre as @coffre" do
        coffre = Coffre.create! valid_attributes
        put :update, {:id => coffre.to_param, :coffre => valid_attributes}, valid_session
        expect(assigns(:coffre)).to eq(coffre)
      end

      it "redirects to the coffre" do
        coffre = Coffre.create! valid_attributes
        put :update, {:id => coffre.to_param, :coffre => valid_attributes}, valid_session
        expect(response).to redirect_to(coffre)
      end
    end

    describe "with invalid params" do
      it "assigns the coffre as @coffre" do
        coffre = Coffre.create! valid_attributes
        put :update, {:id => coffre.to_param, :coffre => invalid_attributes}, valid_session
        expect(assigns(:coffre)).to eq(coffre)
      end

      it "re-renders the 'edit' template" do
        coffre = Coffre.create! valid_attributes
        put :update, {:id => coffre.to_param, :coffre => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coffre" do
      coffre = Coffre.create! valid_attributes
      expect {
        delete :destroy, {:id => coffre.to_param}, valid_session
      }.to change(Coffre, :count).by(-1)
    end

    it "redirects to the coffres list" do
      coffre = Coffre.create! valid_attributes
      delete :destroy, {:id => coffre.to_param}, valid_session
      expect(response).to redirect_to(coffres_url)
    end
  end

end
