require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LivraisonlogsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Livraisonlog. As you add validations to Livraisonlog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LivraisonlogsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all livraisonlogs as @livraisonlogs" do
      livraisonlog = Livraisonlog.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:livraisonlogs)).to eq([livraisonlog])
    end
  end

  describe "GET show" do
    it "assigns the requested livraisonlog as @livraisonlog" do
      livraisonlog = Livraisonlog.create! valid_attributes
      get :show, {:id => livraisonlog.to_param}, valid_session
      expect(assigns(:livraisonlog)).to eq(livraisonlog)
    end
  end

  describe "GET new" do
    it "assigns a new livraisonlog as @livraisonlog" do
      get :new, {}, valid_session
      expect(assigns(:livraisonlog)).to be_a_new(Livraisonlog)
    end
  end

  describe "GET edit" do
    it "assigns the requested livraisonlog as @livraisonlog" do
      livraisonlog = Livraisonlog.create! valid_attributes
      get :edit, {:id => livraisonlog.to_param}, valid_session
      expect(assigns(:livraisonlog)).to eq(livraisonlog)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Livraisonlog" do
        expect {
          post :create, {:livraisonlog => valid_attributes}, valid_session
        }.to change(Livraisonlog, :count).by(1)
      end

      it "assigns a newly created livraisonlog as @livraisonlog" do
        post :create, {:livraisonlog => valid_attributes}, valid_session
        expect(assigns(:livraisonlog)).to be_a(Livraisonlog)
        expect(assigns(:livraisonlog)).to be_persisted
      end

      it "redirects to the created livraisonlog" do
        post :create, {:livraisonlog => valid_attributes}, valid_session
        expect(response).to redirect_to(Livraisonlog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved livraisonlog as @livraisonlog" do
        post :create, {:livraisonlog => invalid_attributes}, valid_session
        expect(assigns(:livraisonlog)).to be_a_new(Livraisonlog)
      end

      it "re-renders the 'new' template" do
        post :create, {:livraisonlog => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested livraisonlog" do
        livraisonlog = Livraisonlog.create! valid_attributes
        put :update, {:id => livraisonlog.to_param, :livraisonlog => new_attributes}, valid_session
        livraisonlog.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested livraisonlog as @livraisonlog" do
        livraisonlog = Livraisonlog.create! valid_attributes
        put :update, {:id => livraisonlog.to_param, :livraisonlog => valid_attributes}, valid_session
        expect(assigns(:livraisonlog)).to eq(livraisonlog)
      end

      it "redirects to the livraisonlog" do
        livraisonlog = Livraisonlog.create! valid_attributes
        put :update, {:id => livraisonlog.to_param, :livraisonlog => valid_attributes}, valid_session
        expect(response).to redirect_to(livraisonlog)
      end
    end

    describe "with invalid params" do
      it "assigns the livraisonlog as @livraisonlog" do
        livraisonlog = Livraisonlog.create! valid_attributes
        put :update, {:id => livraisonlog.to_param, :livraisonlog => invalid_attributes}, valid_session
        expect(assigns(:livraisonlog)).to eq(livraisonlog)
      end

      it "re-renders the 'edit' template" do
        livraisonlog = Livraisonlog.create! valid_attributes
        put :update, {:id => livraisonlog.to_param, :livraisonlog => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested livraisonlog" do
      livraisonlog = Livraisonlog.create! valid_attributes
      expect {
        delete :destroy, {:id => livraisonlog.to_param}, valid_session
      }.to change(Livraisonlog, :count).by(-1)
    end

    it "redirects to the livraisonlogs list" do
      livraisonlog = Livraisonlog.create! valid_attributes
      delete :destroy, {:id => livraisonlog.to_param}, valid_session
      expect(response).to redirect_to(livraisonlogs_url)
    end
  end

end
