require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MonetairesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Monetaire. As you add validations to Monetaire, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonetairesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all monetaires as @monetaires" do
      monetaire = Monetaire.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:monetaires)).to eq([monetaire])
    end
  end

  describe "GET show" do
    it "assigns the requested monetaire as @monetaire" do
      monetaire = Monetaire.create! valid_attributes
      get :show, {:id => monetaire.to_param}, valid_session
      expect(assigns(:monetaire)).to eq(monetaire)
    end
  end

  describe "GET new" do
    it "assigns a new monetaire as @monetaire" do
      get :new, {}, valid_session
      expect(assigns(:monetaire)).to be_a_new(Monetaire)
    end
  end

  describe "GET edit" do
    it "assigns the requested monetaire as @monetaire" do
      monetaire = Monetaire.create! valid_attributes
      get :edit, {:id => monetaire.to_param}, valid_session
      expect(assigns(:monetaire)).to eq(monetaire)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Monetaire" do
        expect {
          post :create, {:monetaire => valid_attributes}, valid_session
        }.to change(Monetaire, :count).by(1)
      end

      it "assigns a newly created monetaire as @monetaire" do
        post :create, {:monetaire => valid_attributes}, valid_session
        expect(assigns(:monetaire)).to be_a(Monetaire)
        expect(assigns(:monetaire)).to be_persisted
      end

      it "redirects to the created monetaire" do
        post :create, {:monetaire => valid_attributes}, valid_session
        expect(response).to redirect_to(Monetaire.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monetaire as @monetaire" do
        post :create, {:monetaire => invalid_attributes}, valid_session
        expect(assigns(:monetaire)).to be_a_new(Monetaire)
      end

      it "re-renders the 'new' template" do
        post :create, {:monetaire => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested monetaire" do
        monetaire = Monetaire.create! valid_attributes
        put :update, {:id => monetaire.to_param, :monetaire => new_attributes}, valid_session
        monetaire.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested monetaire as @monetaire" do
        monetaire = Monetaire.create! valid_attributes
        put :update, {:id => monetaire.to_param, :monetaire => valid_attributes}, valid_session
        expect(assigns(:monetaire)).to eq(monetaire)
      end

      it "redirects to the monetaire" do
        monetaire = Monetaire.create! valid_attributes
        put :update, {:id => monetaire.to_param, :monetaire => valid_attributes}, valid_session
        expect(response).to redirect_to(monetaire)
      end
    end

    describe "with invalid params" do
      it "assigns the monetaire as @monetaire" do
        monetaire = Monetaire.create! valid_attributes
        put :update, {:id => monetaire.to_param, :monetaire => invalid_attributes}, valid_session
        expect(assigns(:monetaire)).to eq(monetaire)
      end

      it "re-renders the 'edit' template" do
        monetaire = Monetaire.create! valid_attributes
        put :update, {:id => monetaire.to_param, :monetaire => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monetaire" do
      monetaire = Monetaire.create! valid_attributes
      expect {
        delete :destroy, {:id => monetaire.to_param}, valid_session
      }.to change(Monetaire, :count).by(-1)
    end

    it "redirects to the monetaires list" do
      monetaire = Monetaire.create! valid_attributes
      delete :destroy, {:id => monetaire.to_param}, valid_session
      expect(response).to redirect_to(monetaires_url)
    end
  end

end
