require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TcoffresController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tcoffre. As you add validations to Tcoffre, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TcoffresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tcoffres as @tcoffres" do
      tcoffre = Tcoffre.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tcoffres)).to eq([tcoffre])
    end
  end

  describe "GET show" do
    it "assigns the requested tcoffre as @tcoffre" do
      tcoffre = Tcoffre.create! valid_attributes
      get :show, {:id => tcoffre.to_param}, valid_session
      expect(assigns(:tcoffre)).to eq(tcoffre)
    end
  end

  describe "GET new" do
    it "assigns a new tcoffre as @tcoffre" do
      get :new, {}, valid_session
      expect(assigns(:tcoffre)).to be_a_new(Tcoffre)
    end
  end

  describe "GET edit" do
    it "assigns the requested tcoffre as @tcoffre" do
      tcoffre = Tcoffre.create! valid_attributes
      get :edit, {:id => tcoffre.to_param}, valid_session
      expect(assigns(:tcoffre)).to eq(tcoffre)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tcoffre" do
        expect {
          post :create, {:tcoffre => valid_attributes}, valid_session
        }.to change(Tcoffre, :count).by(1)
      end

      it "assigns a newly created tcoffre as @tcoffre" do
        post :create, {:tcoffre => valid_attributes}, valid_session
        expect(assigns(:tcoffre)).to be_a(Tcoffre)
        expect(assigns(:tcoffre)).to be_persisted
      end

      it "redirects to the created tcoffre" do
        post :create, {:tcoffre => valid_attributes}, valid_session
        expect(response).to redirect_to(Tcoffre.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tcoffre as @tcoffre" do
        post :create, {:tcoffre => invalid_attributes}, valid_session
        expect(assigns(:tcoffre)).to be_a_new(Tcoffre)
      end

      it "re-renders the 'new' template" do
        post :create, {:tcoffre => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tcoffre" do
        tcoffre = Tcoffre.create! valid_attributes
        put :update, {:id => tcoffre.to_param, :tcoffre => new_attributes}, valid_session
        tcoffre.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tcoffre as @tcoffre" do
        tcoffre = Tcoffre.create! valid_attributes
        put :update, {:id => tcoffre.to_param, :tcoffre => valid_attributes}, valid_session
        expect(assigns(:tcoffre)).to eq(tcoffre)
      end

      it "redirects to the tcoffre" do
        tcoffre = Tcoffre.create! valid_attributes
        put :update, {:id => tcoffre.to_param, :tcoffre => valid_attributes}, valid_session
        expect(response).to redirect_to(tcoffre)
      end
    end

    describe "with invalid params" do
      it "assigns the tcoffre as @tcoffre" do
        tcoffre = Tcoffre.create! valid_attributes
        put :update, {:id => tcoffre.to_param, :tcoffre => invalid_attributes}, valid_session
        expect(assigns(:tcoffre)).to eq(tcoffre)
      end

      it "re-renders the 'edit' template" do
        tcoffre = Tcoffre.create! valid_attributes
        put :update, {:id => tcoffre.to_param, :tcoffre => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tcoffre" do
      tcoffre = Tcoffre.create! valid_attributes
      expect {
        delete :destroy, {:id => tcoffre.to_param}, valid_session
      }.to change(Tcoffre, :count).by(-1)
    end

    it "redirects to the tcoffres list" do
      tcoffre = Tcoffre.create! valid_attributes
      delete :destroy, {:id => tcoffre.to_param}, valid_session
      expect(response).to redirect_to(tcoffres_url)
    end
  end

end
